// ============================================================
// AutoLunex — Rust backend
// Security level: 7.5/10
//   • URL split into 6 segments with different XOR keys
//   • obfstr!() compile-time encryption (random key per build)
//   • Anti-debug: IsDebuggerPresent + timing (release only)
//   • Checksummed license state (tamper-detect)
//   • Scattered #[inline(never)] canary gates
//   • zeroize sensitive data after use
//   • No files/folders created on user's machine
//   • Deception matrix: 15 exotic-language layers, reshuffled every build
// ============================================================

// Generated by build.rs — unique per compilation.
// 15 language layers (Mongolian, Tibetan, Cherokee…) with random XOR keys.
// Reverse engineers find a maze of fake secrets in unreadable scripts.
include!(concat!(env!("OUT_DIR"), "/decoy_matrix.rs"));

use hmac::{Hmac, Mac};
use obfstr::obfstr;
use serde::Serialize;
use sha2::Sha256;
use std::fmt::Write;
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::Mutex;
use tauri::{AppHandle, Emitter};
use zeroize::Zeroize;

type HmacSha256 = Hmac<Sha256>;

// ============================================================
// CHECKSUMMED LICENSE STATE
// Hacker patches LIC_STATE byte → checksum mismatch → exit(0)
// Cannot simply flip a bool — must know the magic formula
// ============================================================
const LIC_MAGIC: u64 = 0xCAFE_BABE_DEAD_BEEF;
const LIC_SALT: u64 = 0xF00D_C0DE_1337_FEED;
const LIC_INIT_CHECK: u64 = 0u64.wrapping_mul(LIC_SALT) ^ LIC_SALT.rotate_right(13);

static LIC_STATE: AtomicU64 = AtomicU64::new(0);
static LIC_CHECK: AtomicU64 = AtomicU64::new(LIC_INIT_CHECK);
static LICENSE_KEY_STORE: Mutex<Option<String>> = Mutex::new(None);

fn lic_set(valid: bool) {
  let v: u64 = if valid { LIC_MAGIC } else { 0 };
  let c: u64 = v.wrapping_mul(LIC_SALT) ^ LIC_SALT.rotate_right(13);
  LIC_STATE.store(v, Ordering::SeqCst);
  LIC_CHECK.store(c, Ordering::SeqCst);
}

/// Called at every gate — detects memory tampering
fn lic_ok() -> bool {
  let v = LIC_STATE.load(Ordering::SeqCst);
  let c = LIC_CHECK.load(Ordering::SeqCst);
  let expected = v.wrapping_mul(LIC_SALT) ^ LIC_SALT.rotate_right(13);
  if c != expected {
    // Tamper detected: checksum doesn't match -> block access safely
    return false;
  }
  v == LIC_MAGIC
}

// ============================================================
// SCATTERED CANARY GATES (each #[inline(never)] so they appear
// as distinct call sites in assembly — cannot NOP just one)
// ============================================================
#[inline(never)]
fn gate_verify() -> bool {
  lic_ok()
}

#[inline(never)]
fn gate_network() -> bool {
  lic_ok()
}

#[inline(never)]
fn gate_xsmm() -> bool {
  lic_ok()
}

// ============================================================
// ANTI-DEBUG (release builds only, Windows only)
// ============================================================
#[cfg(all(windows, not(debug_assertions)))]
fn anti_debug() {
  #[link(name = "kernel32")]
  extern "system" {
    fn IsDebuggerPresent() -> i32;
    fn CheckRemoteDebuggerPresent(
      hProcess: *mut std::ffi::c_void,
      pbDebuggerPresent: *mut i32,
    ) -> i32;
    fn GetCurrentProcess() -> *mut std::ffi::c_void;
    fn GetModuleHandleA(lpModuleName: *const u8) -> *mut std::ffi::c_void;
  }
  #[link(name = "user32")]
  extern "system" {
    fn FindWindowA(lpClassName: *const u8, lpWindowName: *const u8) -> *mut std::ffi::c_void;
  }

  #[allow(unsafe_code)]
  unsafe {
    // 1. Kiểm tra debugger trực tiếp
    if IsDebuggerPresent() != 0 {
      std::process::exit(0);
    }
    let mut is_remote = 0i32;
    if CheckRemoteDebuggerPresent(GetCurrentProcess(), &mut is_remote) != 0 && is_remote != 0 {
      std::process::exit(0);
    }

    // 2. Chống Hook / Sniffer: Quét các DLL hook thường gặp (Frida, Detours, MinHook, Cuckoo...)
    let bad_dlls: &[&[u8]] = &[
      b"frida-agent.dll\0",
      b"frida-gadget.dll\0",
      b"frida.dll\0",
      b"cuckoomon.dll\0",
      b"hookdetector.dll\0",
      b"scylla_hide.dll\0",
      b"detours.dll\0",
      b"minhook.dll\0",
      b"httpdebugger.dll\0",
      b"fiddler.dll\0",
    ];
    for &dll in bad_dlls {
      if !GetModuleHandleA(dll.as_ptr()).is_null() {
        std::process::exit(0);
      }
    }

    // 3. Chống Frida Named Pipes: Kiểm tra pipe mặc định của Frida server
    let bad_pipes = [r"\\.\pipe\frida", r"\\.\pipe\linjector"];
    for pipe in bad_pipes {
      if std::path::Path::new(pipe).exists() {
        std::process::exit(0);
      }
    }

    // 4. Quét cửa sổ các công cụ bắt gói tin & hook đang chạy (Fiddler, Charles, Wireshark, HTTPDebugger...)
    let bad_windows: &[&[u8]] = &[
      b"Fiddler\0",
      b"Wireshark\0",
      b"Charles\0",
      b"HTTPDebuggerUI\0",
      b"Burp Suite\0",
      b"x64dbg\0",
      b"x32dbg\0",
      b"Cheat Engine\0",
    ];
    for &win_name in bad_windows {
      if !FindWindowA(std::ptr::null(), win_name.as_ptr()).is_null() {
        std::process::exit(0);
      }
    }
  }
}

#[cfg(not(all(windows, not(debug_assertions))))]
#[inline(always)]
fn anti_debug() {}

// ============================================================
// URL ASSEMBLY — 6 segments with different XOR keys
// Hacker seeing the binary finds 6 separate byte arrays with
// different keys, no string appears contiguous in memory.
// "https://lunex.io.vn/api/license.php" assembled at runtime.
// ============================================================

// "https://" XOR 0x7F
const U1: &[u8] = &[0x17, 0x0B, 0x0B, 0x0F, 0x0C, 0x45, 0x50, 0x50];
// "lunex" XOR 0x3C
const U2: &[u8] = &[0x50, 0x49, 0x52, 0x59, 0x44];
// ".io.vn" XOR 0x1A
const U3: &[u8] = &[0x34, 0x73, 0x75, 0x34, 0x6C, 0x74];
// "/api/" XOR 0xA3
const U4: &[u8] = &[0x8C, 0xC2, 0xD3, 0xCA, 0x8C];
// "license" XOR 0x4D
const U5: &[u8] = &[0x21, 0x24, 0x2E, 0x28, 0x23, 0x3E, 0x28];
// ".php" XOR 0xE2
const U6: &[u8] = &[0xCC, 0x92, 0x8A, 0x92];

// XOR keys per segment (different for each = no pattern in binary)
const K1: u8 = 0x7F;
const K2: u8 = 0x3C;
const K3: u8 = 0x1A;
const K4: u8 = 0xA3;
const K5: u8 = 0x4D;
const K6: u8 = 0xE2;

#[inline(never)]
fn build_api_url() -> String {
  let mut url = String::with_capacity(35);
  for &b in U1 {
    url.push((b ^ K1) as char);
  }
  for &b in U2 {
    url.push((b ^ K2) as char);
  }
  for &b in U3 {
    url.push((b ^ K3) as char);
  }
  for &b in U4 {
    url.push((b ^ K4) as char);
  }
  for &b in U5 {
    url.push((b ^ K5) as char);
  }
  for &b in U6 {
    url.push((b ^ K6) as char);
  }
  url
}

// ============================================================
// HWID — Windows MachineGuid from Registry (not cmd/powershell)
// ============================================================
fn get_hwid() -> String {
  #[cfg(windows)]
  {
    use winreg::enums::HKEY_LOCAL_MACHINE;
    use winreg::RegKey;
    let hklm = RegKey::predef(HKEY_LOCAL_MACHINE);
    if let Ok(sub) = hklm.open_subkey(r"SOFTWARE\Microsoft\Cryptography") {
      if let Ok(guid) = sub.get_value::<String, _>("MachineGuid") {
        return guid;
      }
    }
  }
  // Fallback: hash of environment identifiers
  let raw = [
    std::env::var("COMPUTERNAME").unwrap_or_default(),
    std::env::var("USERNAME").unwrap_or_default(),
  ]
  .join("-");
  use sha2::{Digest, Sha256 as S2};
  let hash = S2::digest(raw.as_bytes());
  let mut hex = String::new();
  for b in &hash {
    let _ = write!(hex, "{:02x}", b);
  }
  hex
}

// ============================================================
// HMAC-SHA256 Signature Verification
// ============================================================
fn verify_hmac(secret: &str, data_json: &str, received: &str) -> bool {
  let Ok(mut mac) = HmacSha256::new_from_slice(secret.as_bytes()) else {
    return false;
  };
  mac.update(data_json.as_bytes());
  let result = mac.finalize().into_bytes();
  let mut computed = String::new();
  for b in result.iter() {
    let _ = write!(computed, "{:02x}", b);
  }
  computed == received
}

fn compute_hmac(secret: &str, data: &str) -> String {
  let Ok(mut mac) = HmacSha256::new_from_slice(secret.as_bytes()) else {
    return String::new();
  };
  mac.update(data.as_bytes());
  let result = mac.finalize().into_bytes();
  let mut computed = String::new();
  for b in result.iter() {
    let _ = write!(computed, "{:02x}", b);
  }
  computed
}

#[allow(dead_code)]
fn url_encode(s: &str) -> String {
  let mut out = String::with_capacity(s.len());
  for byte in s.bytes() {
    match byte {
      b'A'..=b'Z' | b'a'..=b'z' | b'0'..=b'9' | b'-' | b'_' | b'.' | b'~' => {
        out.push(byte as char);
      }
      _ => {
        let _ = write!(out, "%{:02X}", byte);
      }
    }
  }
  out
}

// ============================================================
// License result returned to the frontend
// ============================================================
#[derive(Serialize, Debug, Clone)]
pub struct LicenseResult {
  pub success: bool,
  pub status: String,
  pub message: String,
  #[serde(skip_serializing_if = "Option::is_none")]
  pub days_left: Option<f64>,
  #[serde(skip_serializing_if = "Option::is_none")]
  pub expired_at: Option<String>,
  #[serde(skip_serializing_if = "Option::is_none")]
  pub buyer: Option<String>,
}

// ============================================================
// VERIFY_LICENSE — main Tauri command
// ============================================================
#[tauri::command]
fn verify_license(key: String) -> LicenseResult {
  // Anti-debug check on every verify attempt
  anti_debug();

  let mut trimmed = key.trim().to_string();
  if trimmed.is_empty() {
    return LicenseResult {
      success: false,
      status: "missing_key".into(),
      message: "Vui lòng nhập mã key bản quyền!".into(),
      days_left: None,
      expired_at: None,
      buyer: None,
    };
  }

  // Get HWID
  let hwid = get_hwid();
  let app_slug = obfstr!("lunexpc").to_string();
  let mut api_url = build_api_url();

  // ── Dynamic Cryptographic Handshake (t, nonce, sign) ──────────
  let t = std::time::SystemTime::now()
    .duration_since(std::time::UNIX_EPOCH)
    .unwrap_or_default()
    .as_secs();

  // Generate 16-hex nonce using OS timestamp and thread id
  let nonce = {
    use sha2::{Digest, Sha256};
    let seed = format!("{}-{}-{}", t, std::process::id(), trimmed);
    let hash = Sha256::digest(seed.as_bytes());
    let mut s = String::with_capacity(32);
    for b in hash.iter().take(16) {
      let _ = write!(s, "{:02x}", b);
    }
    s
  };

  // Sign request: hash_hmac('sha256', key + '|' + hwid + '|' + t + '|' + nonce, SECRET_KEY)
  let sign = {
    let mut secret = obfstr!("LUNEX_UNIVERSAL_KEY_SECRET_@2026#SECURE").to_string();
    let payload = format!("{}|{}|{}|{}", trimmed, hwid, t, nonce);
    let sig = compute_hmac(&secret, &payload);
    secret.zeroize();
    sig
  };

  // Build JSON body for POST request
  let req_body = serde_json::json!({
    "key": trimmed,
    "hwid": hwid,
    "app": app_slug,
    "t": t,
    "nonce": nonce,
    "sign": sign,
  })
  .to_string();

  // Call API via curl POST (no direct browser GET)
  #[cfg(windows)]
  let mut cmd = std::process::Command::new("curl.exe");
  #[cfg(not(windows))]
  let mut cmd = std::process::Command::new("curl");

  cmd
    .arg("-s")
    .arg("-X")
    .arg("POST")
    .arg("-H")
    .arg("Content-Type: application/json")
    .arg("-H")
    .arg("Accept: application/json")
    .arg("-H")
    .arg("User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36")
    .arg("-d")
    .arg("@-") // Read body from stdin pipe — hides payload from Process Monitor/CreateProcess hooks
    .arg("--connect-timeout")
    .arg("10")
    .arg("--max-time")
    .arg("15")
    .arg(&api_url)
    .stdin(std::process::Stdio::piped())
    .stdout(std::process::Stdio::piped())
    .stderr(std::process::Stdio::null());

  api_url.zeroize();

  #[cfg(windows)]
  {
    use std::os::windows::process::CommandExt;
    cmd.creation_flags(0x0800_0000); // CREATE_NO_WINDOW
  }

  let raw = match cmd.spawn() {
    Ok(mut child) => {
      if let Some(mut stdin) = child.stdin.take() {
        use std::io::Write;
        let _ = stdin.write_all(req_body.as_bytes());
      }
      match child.wait_with_output() {
        Ok(o) => String::from_utf8_lossy(&o.stdout).to_string(),
        Err(_) => String::new(),
      }
    }
    Err(_) => String::new(),
  };

  if raw.trim().is_empty() {
    // Network error — check if this exact key was valid in the current session
    if gate_verify() {
      if let Ok(lock) = LICENSE_KEY_STORE.lock() {
        if lock.as_deref() == Some(trimmed.as_str()) {
          trimmed.zeroize();
          return LicenseResult {
            success: true,
            status: "valid".into(),
            message: "Chế độ offline – đã xác thực trước đó.".into(),
            days_left: None,
            expired_at: None,
            buyer: None,
          };
        }
      }
    }
    trimmed.zeroize();
    return LicenseResult {
      success: false,
      status: "network_error".into(),
      message: "Không thể kết nối đến máy chủ xác thực. Vui lòng kiểm tra mạng!".into(),
      days_left: None,
      expired_at: None,
      buyer: None,
    };
  }

  // Parse JSON
  let parsed: serde_json::Value = match serde_json::from_str(raw.trim()) {
    Ok(v) => v,
    Err(_) => {
      trimmed.zeroize();
      return LicenseResult {
        success: false,
        status: "parse_error".into(),
        message: "Phản hồi từ máy chủ không hợp lệ!".into(),
        days_left: None,
        expired_at: None,
        buyer: None,
      };
    }
  };

  let success = parsed["success"].as_bool().unwrap_or(false);
  let status = parsed["status"].as_str().unwrap_or("unknown").to_string();
  let srv_msg = parsed["message"].as_str().unwrap_or("").to_string();

  // ── ANTI-BYPASS: Bidirectional HMAC-SHA256 signature verification ──
  // Server signs with: status + '|' + key + '|' + hwid + '|' + expired_at + '|' + nonce
  if let (Some(data_val), Some(sig)) = (parsed.get("data"), parsed["signature"].as_str()) {
    if !sig.is_empty() {
      let mut hmac_secret = obfstr!("LUNEX_UNIVERSAL_KEY_SECRET_@2026#SECURE").to_string();
      let key_str = data_val["key"].as_str().unwrap_or("");
      let hwid_str = data_val["hwid"].as_str().unwrap_or("");
      let exp_str = data_val["expired_at"].as_str().unwrap_or("");
      let sig_payload = format!("{}|{}|{}|{}|{}", status, key_str, hwid_str, exp_str, nonce);
      let ok = verify_hmac(&hmac_secret, &sig_payload, sig);
      hmac_secret.zeroize(); // immediate wipe after use
      if !ok {
        lic_set(false);
        trimmed.zeroize();
        return LicenseResult {
          success: false,
          status: "signature_invalid".into(),
          message: "Phát hiện giả mạo máy chủ! Kết nối bị chặn vì lý do bảo mật.".into(),
          days_left: None,
          expired_at: None,
          buyer: None,
        };
      }
    }
  }

  if success && status == "valid" {
    lic_set(true);
    if let Ok(mut lock) = LICENSE_KEY_STORE.lock() {
      *lock = Some(trimmed.clone());
    }
    trimmed.zeroize();

    let days_left = parsed["data"]["days_left"].as_f64();
    let expired_at = parsed["data"]["expired_at"]
      .as_str()
      .filter(|s| !s.is_empty())
      .map(str::to_string);
    // Nhận username từ API mới (hoặc fallback buyer)
    let buyer = parsed["data"]["username"]
      .as_str()
      .or_else(|| parsed["data"]["buyer"].as_str())
      .filter(|s| !s.is_empty())
      .map(str::to_string);

    LicenseResult {
      success: true,
      status,
      message: srv_msg,
      days_left,
      expired_at,
      buyer,
    }
  } else {
    lic_set(false);
    if let Ok(mut lock) = LICENSE_KEY_STORE.lock() {
      *lock = None;
    }
    trimmed.zeroize();

    let friendly = match status.as_str() {
      "wrong_device" => {
        "Key này đang chạy trên máy khác! Vui lòng vào web Lunex để Reset thiết bị.".to_string()
      }
      "app_mismatch" => "Mã key này không thuộc về ứng dụng này!".to_string(),
      "key_expired" => "Bản quyền của bạn đã hết hạn! Vui lòng gia hạn thêm.".to_string(),
      "invalid_key" => "Mã key không hợp lệ hoặc chưa được mua!".to_string(),
      "key_revoked" => "Bản quyền này đã bị thu hồi do vi phạm điều khoản!".to_string(),
      "rate_limited" => {
        "Bạn đã gửi quá nhiều yêu cầu xác thực. Vui lòng thử lại sau 1 phút!".to_string()
      }
      _ => srv_msg,
    };

    LicenseResult {
      success: false,
      status,
      message: friendly,
      days_left: None,
      expired_at: None,
      buyer: None,
    }
  }
}

// ============================================================
// System info
// ============================================================
#[derive(Serialize)]
pub struct SystemInfo {
  pub app_version: String,
  pub os: String,
  pub arch: String,
  pub portable: bool,
}

#[tauri::command]
fn get_system_info() -> SystemInfo {
  let is_portable = {
    #[cfg(windows)]
    {
      if let Ok(exe) = std::env::current_exe() {
        if let Some(parent) = exe.parent() {
          parent.join(".portable").exists()
        } else {
          false
        }
      } else {
        false
      }
    }
    #[cfg(not(windows))]
    {
      false
    }
  };

  SystemInfo {
    app_version: env!("CARGO_PKG_VERSION").to_string(),
    os: std::env::consts::OS.to_string(),
    arch: std::env::consts::ARCH.to_string(),
    portable: is_portable,
  }
}

#[tauri::command]
fn confirm_quit(app: AppHandle) {
  app.exit(0);
}

// ============================================================
// Storage drive migration & management
// ============================================================
#[derive(Serialize)]
pub struct MigrateResult {
  pub success: bool,
  pub target_path: String,
  pub exe_copied: bool,
  pub message: String,
}

#[tauri::command]
fn get_available_drives() -> Vec<String> {
  let mut drives = Vec::new();
  #[cfg(windows)]
  {
    for letter in b'C'..=b'Z' {
      let path_str = format!("{}:\\", letter as char);
      if std::path::Path::new(&path_str).exists() {
        drives.push(format!("{}:", letter as char));
      }
    }
  }
  if drives.is_empty() {
    drives.push("C:".to_string());
  }
  drives
}

#[tauri::command]
fn get_current_storage_drive() -> String {
  #[cfg(windows)]
  {
    for letter in b'D'..=b'Z' {
      let candidate = format!("{}:\\AutoLunex\\.portable", letter as char);
      if std::path::Path::new(&candidate).exists() {
        return format!("{}:", letter as char);
      }
    }
    if let Ok(exe) = std::env::current_exe() {
      let exe_str = exe.to_string_lossy().to_uppercase();
      if exe_str.len() >= 2 && exe_str.as_bytes()[1] == b':' {
        return exe_str[..2].to_string();
      }
    }
  }
  "C:".to_string()
}

#[allow(clippy::collapsible_if, clippy::cmp_owned)]
#[tauri::command]
fn migrate_app_to_drive(target_drive: String, data_json: String) -> Result<MigrateResult, String> {
  let drive = target_drive.trim_end_matches(['\\', '/']).to_uppercase();
  #[cfg(windows)]
  {
    let drive_root = format!("{}\\", drive);
    if !std::path::Path::new(&drive_root).exists() {
      return Err(format!("Ổ đĩa {} không tồn tại trên hệ thống.", drive));
    }

    let target_dir = format!("{}\\AutoLunex", drive);
    let data_dir = format!("{}\\data", target_dir);
    let webview_dir = format!("{}\\webview_data", target_dir);

    std::fs::create_dir_all(&data_dir).map_err(|e| format!("Lỗi tạo thư mục dữ liệu: {}", e))?;
    std::fs::create_dir_all(&webview_dir).map_err(|e| format!("Lỗi tạo thư mục webview: {}", e))?;

    let portable_file = format!("{}\\.portable", target_dir);
    let _ = std::fs::write(&portable_file, "portable");

    let storage_file = format!("{}\\autolunex_storage.json", data_dir);
    std::fs::write(&storage_file, &data_json)
      .map_err(|e| format!("Lỗi ghi file dữ liệu: {}", e))?;

    let mut exe_copied = false;
    if let Ok(current_exe) = std::env::current_exe() {
      let dest_exe = format!("{}\\AutoLunex.exe", target_dir);
      let dest_path = std::path::Path::new(&dest_exe);
      if current_exe.as_path() != dest_path && std::fs::copy(&current_exe, dest_path).is_ok() {
        exe_copied = true;
      }
      if let Some(parent) = current_exe.parent() {
        if let Ok(entries) = std::fs::read_dir(parent) {
          for entry in entries.flatten() {
            let p = entry.path();
            if p
              .extension()
              .is_some_and(|ext| ext.eq_ignore_ascii_case("dll"))
            {
              if let Some(fname) = p.file_name() {
                let dest_dll = format!("{}\\{}", target_dir, fname.to_string_lossy());
                let _ = std::fs::copy(&p, &dest_dll);
              }
            }
          }
        }
      }
    }

    #[allow(unused_unsafe)]
    unsafe {
      std::env::set_var("WEBVIEW2_USER_DATA_FOLDER", &webview_dir);
    }

    Ok(MigrateResult {
      success: true,
      target_path: target_dir.clone(),
      exe_copied,
      message: format!(
        "Đã chuyển toàn bộ dữ liệu và ứng dụng sang {}. Tuyệt đối không còn lưu vào ổ C.",
        target_dir
      ),
    })
  }
  #[cfg(not(windows))]
  {
    let _ = (drive, data_json);
    Err("Chỉ hỗ trợ trên Windows.".to_string())
  }
}

#[tauri::command]
fn read_drive_data(target_drive: String) -> Result<String, String> {
  let drive = target_drive.trim_end_matches(['\\', '/']).to_uppercase();
  #[cfg(windows)]
  {
    let data_file = format!("{}\\AutoLunex\\data\\autolunex_storage.json", drive);
    if std::path::Path::new(&data_file).exists() {
      std::fs::read_to_string(&data_file).map_err(|e| format!("Lỗi đọc file dữ liệu: {}", e))
    } else {
      Err("Chưa có file dữ liệu trên ổ đĩa này".to_string())
    }
  }
  #[cfg(not(windows))]
  {
    let _ = drive;
    Err("Không hỗ trợ".to_string())
  }
}

#[tauri::command]
fn open_storage_folder(path: String) -> Result<bool, String> {
  #[cfg(windows)]
  {
    use std::process::Command;
    let _ = Command::new("explorer.exe")
      .arg(&path)
      .spawn()
      .map_err(|e| format!("Không thể mở thư mục: {}", e))?;
    Ok(true)
  }
  #[cfg(not(windows))]
  {
    let _ = path;
    Ok(false)
  }
}

// ============================================================
// XSMM request — protected by license gates
// ============================================================
#[tauri::command]
async fn xsmm_request(
  url: String,
  method: String,
  token: String,
  body: Option<String>,
) -> Result<String, String> {
  // Gate A — checks checksummed state
  if !gate_xsmm() {
    return Err("E_UNLICENSED".to_string());
  }

  tauri::async_runtime::spawn_blocking(move || {
    #[cfg(windows)]
    let mut cmd = std::process::Command::new("curl.exe");
    #[cfg(not(windows))]
    let mut cmd = std::process::Command::new("curl");

    cmd
      .arg("-s")
      .arg("-X")
      .arg(&method)
      .arg("-H")
      .arg(format!("Authorization: Bearer {}", token.trim()))
      .arg("-H")
      .arg("Content-Type: application/json")
      .arg("--connect-timeout")
      .arg("5")
      .arg("--max-time")
      .arg("15");

    if let Some(ref b) = body {
      cmd.arg("-d").arg(b);
    }
    cmd.arg(&url);

    #[cfg(windows)]
    {
      use std::os::windows::process::CommandExt;
      cmd.creation_flags(0x0800_0000);
    }

    let output = cmd
      .output()
      .map_err(|e| format!("Failed to execute curl: {}", e))?;
    let stdout = String::from_utf8_lossy(&output.stdout);

    if !output.status.success() && stdout.trim().is_empty() {
      let err = String::from_utf8_lossy(&output.stderr);
      return Err(format!("XSMM server connection error: {}", err));
    }

    // Gate B — second canary deep in function body
    if !gate_xsmm() {
      return Err("E_UNLICENSED".to_string());
    }

    Ok(stdout.into_owned())
  })
  .await
  .map_err(|e| format!("Task join error: {}", e))?
}

// ============================================================
// Curl request — protected by license gates
// ============================================================
#[tauri::command]
#[allow(clippy::too_many_arguments)]
async fn curl_request(
  url: String,
  method: Option<String>,
  headers: Option<Vec<String>>,
  body: Option<String>,
  cookie: Option<String>,
  proxy: Option<String>,
  include_headers: Option<bool>,
  timeout_secs: Option<u64>,
  form_fields: Option<Vec<String>>,
) -> Result<String, String> {
  // Gate A
  if !gate_network() {
    return Err("E_UNLICENSED".to_string());
  }

  tauri::async_runtime::spawn_blocking(move || {
    #[cfg(windows)]
    let mut cmd = std::process::Command::new("curl.exe");
    #[cfg(not(windows))]
    let mut cmd = std::process::Command::new("curl");

    let m = method.unwrap_or_else(|| "GET".to_string());
    let t = timeout_secs.unwrap_or(12);
    let max_time_str = t.to_string();
    let conn_time_str = t.min(5).to_string();

    cmd
      .arg("-sS")
      .arg("-k")
      .arg("-g")
      .arg("-L")
      .arg("-X")
      .arg(&m)
      .arg("--connect-timeout")
      .arg(&conn_time_str)
      .arg("--max-time")
      .arg(&max_time_str);

    if include_headers.unwrap_or(false) {
      cmd.arg("-i");
    }
    if let Some(hdrs) = headers {
      for h in hdrs {
        cmd.arg("-H").arg(h);
      }
    }
    if let Some(c) = cookie {
      cmd.arg("-b").arg(c);
    }
    if let Some(p) = proxy {
      let pt = p.trim();
      if !pt.is_empty()
        && pt != "Chưa chọn"
        && pt != "Chua chon"
        && pt != "—"
        && pt != "-"
        && pt != "none"
        && pt != "null"
        && pt.contains(':')
      {
        cmd.arg("-x").arg(pt);
      }
    }
    if let Some(ref b) = body {
      cmd.arg("-d").arg(b);
    }
    if let Some(fields) = form_fields {
      for f in fields {
        let sanitized = if f.starts_with("source=@") {
          let path_part = &f["source=@".len()..];
          format!("source=@{}", path_part.replace('\\', "/"))
        } else {
          f
        };
        cmd.arg("-F").arg(sanitized);
      }
    }
    cmd.arg(&url);

    #[cfg(windows)]
    {
      use std::os::windows::process::CommandExt;
      cmd.creation_flags(0x0800_0000);
    }

    let output = cmd
      .output()
      .map_err(|e| format!("Failed to execute curl: {}", e))?;

    // Gate B — second canary at output stage
    if !gate_network() {
      return Err("E_UNLICENSED".to_string());
    }

    let stdout = String::from_utf8_lossy(&output.stdout);
    if stdout.trim().is_empty() && !output.status.success() {
      let stderr = String::from_utf8_lossy(&output.stderr);
      let err_msg = if stderr.trim().is_empty() {
        format!("Curl exited with status: {}", output.status)
      } else {
        format!("Curl error: {}", stderr.trim())
      };
      return Err(err_msg);
    }
    Ok(stdout.into_owned())
  })
  .await
  .map_err(|e| format!("Task join error: {}", e))?
}

// ============================================================
// In-App Background Updater & Auto-launcher
// ============================================================
#[derive(Clone, Serialize)]
pub struct UpdateProgressPayload {
  pub downloaded: u64,
  pub total: u64,
  pub percent: f64,
  pub status: String,
  pub message: String,
}

#[tauri::command]
async fn fetch_remote_version_json(url: String) -> Result<String, String> {
  tauri::async_runtime::spawn_blocking(move || {
    #[cfg(windows)]
    let mut cmd = std::process::Command::new("curl.exe");
    #[cfg(not(windows))]
    let mut cmd = std::process::Command::new("curl");

    cmd
      .arg("-s")
      .arg("-L")
      .arg("--connect-timeout")
      .arg("8")
      .arg(&url);

    #[cfg(windows)]
    {
      use std::os::windows::process::CommandExt;
      cmd.creation_flags(0x0800_0000);
    }

    let output = cmd.output().map_err(|e| format!("Curl error: {}", e))?;
    let stdout = String::from_utf8_lossy(&output.stdout);
    Ok(stdout.into_owned())
  })
  .await
  .map_err(|e| format!("Task join error: {}", e))?
}

#[tauri::command]
#[allow(clippy::collapsible_if, clippy::unnecessary_wraps)]
async fn start_app_update(
  app: AppHandle,
  window: tauri::Window,
  download_url: String,
) -> Result<String, String> {
  tauri::async_runtime::spawn_blocking(move || {
    let temp_dir = std::env::temp_dir();
    let target_file = temp_dir.join("AutoLunex_Update.exe");

    if target_file.exists() {
      let _ = std::fs::remove_file(&target_file);
    }

    let mut total_bytes = 0u64;
    {
      #[cfg(windows)]
      let mut head_cmd = std::process::Command::new("curl.exe");
      #[cfg(not(windows))]
      let mut head_cmd = std::process::Command::new("curl");

      head_cmd
        .arg("-s")
        .arg("-I")
        .arg("-L")
        .arg("--connect-timeout")
        .arg("10")
        .arg(&download_url);

      #[cfg(windows)]
      {
        use std::os::windows::process::CommandExt;
        head_cmd.creation_flags(0x0800_0000);
      }

      if let Ok(output) = head_cmd.output() {
        let headers = String::from_utf8_lossy(&output.stdout);
        for line in headers.lines() {
          let lower = line.to_lowercase();
          if lower.starts_with("content-length:") {
            if let Some(val) = line.split(':').nth(1) {
              if let Ok(num) = val.trim().parse::<u64>() {
                if num > 0 {
                  total_bytes = num;
                }
              }
            }
          }
        }
      }
    }

    let _ = window.emit(
      "app-update-progress",
      UpdateProgressPayload {
        downloaded: 0,
        total: total_bytes,
        percent: 0.0,
        status: "downloading".to_string(),
        message: "Đang bắt đầu tải bản cập nhật...".to_string(),
      },
    );

    #[cfg(windows)]
    let mut dl_cmd = std::process::Command::new("curl.exe");
    #[cfg(not(windows))]
    let mut dl_cmd = std::process::Command::new("curl");

    dl_cmd
      .arg("-L")
      .arg("-f")
      .arg("-s")
      .arg("--connect-timeout")
      .arg("15")
      .arg("--retry")
      .arg("3")
      .arg("-o")
      .arg(&target_file)
      .arg(&download_url);

    #[cfg(windows)]
    {
      use std::os::windows::process::CommandExt;
      dl_cmd.creation_flags(0x0800_0000);
    }

    let mut child = dl_cmd
      .spawn()
      .map_err(|e| format!("Không thể khởi chạy curl để tải: {}", e))?;

    let mut downloaded_bytes = 0u64;
    loop {
      match child.try_wait() {
        Ok(Some(status)) => {
          if !status.success() {
            let _ = window.emit(
              "app-update-progress",
              UpdateProgressPayload {
                downloaded: downloaded_bytes,
                total: total_bytes,
                percent: 0.0,
                status: "error".to_string(),
                message: "Tải bản cập nhật thất bại. Vui lòng thử lại.".to_string(),
              },
            );
            return Err("Tải bản cập nhật thất bại".to_string());
          }
          break;
        }
        Ok(None) => {
          if let Ok(meta) = std::fs::metadata(&target_file) {
            downloaded_bytes = meta.len();
            let pct = if total_bytes > 0 {
              ((downloaded_bytes as f64 / total_bytes as f64) * 100.0).min(99.0)
            } else {
              0.0
            };
            let _ = window.emit(
              "app-update-progress",
              UpdateProgressPayload {
                downloaded: downloaded_bytes,
                total: total_bytes,
                percent: pct,
                status: "downloading".to_string(),
                message: "Đang tải dữ liệu bản mới...".to_string(),
              },
            );
          }
          std::thread::sleep(std::time::Duration::from_millis(250));
        }
        Err(e) => {
          return Err(format!("Lỗi kiểm tra tiến trình tải: {}", e));
        }
      }
    }

    let final_size = std::fs::metadata(&target_file)
      .map(|m| m.len())
      .unwrap_or(downloaded_bytes);

    if final_size == 0 {
      let _ = window.emit(
        "app-update-progress",
        UpdateProgressPayload {
          downloaded: 0,
          total: total_bytes,
          percent: 0.0,
          status: "error".to_string(),
          message: "File tải về không hợp lệ.".to_string(),
        },
      );
      return Err("File tải về không hợp lệ".to_string());
    }

    let _ = window.emit(
      "app-update-progress",
      UpdateProgressPayload {
        downloaded: final_size,
        total: final_size,
        percent: 100.0,
        status: "launching".to_string(),
        message: "Tải hoàn tất! Đang khởi chạy phiên bản mới...".to_string(),
      },
    );

    std::thread::sleep(std::time::Duration::from_millis(600));

    #[cfg(windows)]
    {
      use std::os::windows::process::CommandExt;
      const CREATE_NEW_PROCESS_GROUP: u32 = 0x0000_0200;
      const DETACHED_PROCESS: u32 = 0x0000_0008;
      let _ = std::process::Command::new(&target_file)
        .creation_flags(CREATE_NEW_PROCESS_GROUP | DETACHED_PROCESS)
        .spawn();
    }
    #[cfg(not(windows))]
    {
      let _ = std::process::Command::new(&target_file).spawn();
    }

    std::thread::sleep(std::time::Duration::from_millis(800));
    app.exit(0);
    Ok("OK".to_string())
  })
  .await
  .map_err(|e| format!("Task join error: {}", e))?
}

#[tauri::command]
fn start_golike_bridge() -> Result<bool, String> {
  if std::net::TcpStream::connect("127.0.0.1:18899").is_ok() {
    return Ok(true);
  }

  #[cfg(windows)]
  {
    use std::os::windows::process::CommandExt;
    const CREATE_NO_WINDOW: u32 = 0x0800_0000;
    const DETACHED_PROCESS: u32 = 0x0000_0008;

    let candidates = [
      r"C:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages\playwright\driver\node.exe",
      r"node.exe",
      r"node",
    ];

    let script_candidates = [
      r"D:\browser\scripts\golike-login.cjs",
      r"D:\AutoLunex\scripts\golike-login.cjs",
      r"scripts\golike-login.cjs",
    ];

    let script_path = script_candidates
      .iter()
      .find(|s| std::path::Path::new(s).exists())
      .copied()
      .unwrap_or(r"D:\browser\scripts\golike-login.cjs");

    for exe in candidates {
      if std::path::Path::new(exe).exists() || exe == "node" || exe == "node.exe" {
        let mut cmd = std::process::Command::new(exe);
        cmd.arg(script_path);
        if let Some(parent) = std::path::Path::new(script_path).parent() {
          cmd.current_dir(parent);
        }
        cmd.creation_flags(CREATE_NO_WINDOW | DETACHED_PROCESS);
        if cmd.spawn().is_ok() {
          std::thread::sleep(std::time::Duration::from_millis(600));
          if std::net::TcpStream::connect("127.0.0.1:18899").is_ok() {
            return Ok(true);
          }
        }
      }
    }
  }

  Ok(std::net::TcpStream::connect("127.0.0.1:18899").is_ok())
}

#[tauri::command]
fn clear_golike_session() -> Result<bool, String> {
  // 1. Delete session files on disk
  let session_paths = [
    r"D:\AutoLunex\golike_session.json",
    r"D:\browser\golike_session.json",
  ];
  for p in session_paths {
    if std::path::Path::new(p).exists() {
      let _ = std::fs::remove_file(p);
    }
  }

  // 2. Wipe LevelDB files for WebView so it starts completely clean on login page
  let local_app_data = std::env::var("LOCALAPPDATA").unwrap_or_default();
  let db_dirs = [
    format!(r"{}\com.autolunex.app\EBWebView\Default\Local Storage\leveldb", local_app_data),
    r"D:\AutoLunex\webview_data\Default\Local Storage\leveldb".to_string(),
  ];

  for db_dir in db_dirs {
    let p = std::path::Path::new(&db_dir);
    if p.exists() {
      if let Ok(entries) = std::fs::read_dir(p) {
        for entry in entries.flatten() {
          let path = entry.path();
          if let Some(ext) = path.extension().and_then(|s| s.to_str()) {
            if ext == "ldb" || ext == "log" {
              if std::fs::remove_file(&path).is_err() {
                let _ = std::fs::write(&path, b"");
              }
            }
          }
        }
      }
    }
  }

  Ok(true)
}

#[tauri::command]
fn extract_golike_session() -> Result<serde_json::Value, String> {
  let candidates = [
    r"C:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages\playwright\driver\node.exe",
    r"node.exe",
    r"node",
  ];

  let script_candidates = [
    r"D:\browser\scripts\golike-login.cjs",
    r"D:\AutoLunex\scripts\golike-login.cjs",
    r"scripts\golike-login.cjs",
  ];

  let script_path = script_candidates
    .iter()
    .find(|s| std::path::Path::new(s).exists())
    .copied()
    .unwrap_or(r"D:\browser\scripts\golike-login.cjs");

  for exe in candidates {
    if std::path::Path::new(exe).exists() || exe == "node" || exe == "node.exe" {
      let mut cmd = std::process::Command::new(exe);
      cmd.arg(script_path);
      cmd.arg("--extract");
      #[cfg(windows)]
      {
        use std::os::windows::process::CommandExt;
        cmd.creation_flags(0x0800_0000); // CREATE_NO_WINDOW
      }
      if let Ok(output) = cmd.output() {
        if output.status.success() {
          let text = String::from_utf8_lossy(&output.stdout).trim().to_string();
          if let Ok(val) = serde_json::from_str::<serde_json::Value>(&text) {
            return Ok(val);
          }
        }
      }
    }
  }

  // Fallback nếu không có node: đọc trực tiếp từ session json file
  let session_paths = [
    r"D:\AutoLunex\golike_session.json",
    r"D:\browser\golike_session.json",
  ];
  for p in session_paths {
    if let Ok(content) = std::fs::read_to_string(p) {
      if let Ok(val) = serde_json::from_str::<serde_json::Value>(&content) {
        if let Some(tok) = val.get("golike_token").and_then(|t| t.as_str()) {
          if !tok.is_empty() {
            let u = val.get("golike_username").and_then(|u| u.as_str()).unwrap_or("GoLike User");
            return Ok(serde_json::json!({
              "success": true,
              "hasSession": true,
              "user": {
                "username": u,
                "balance": "0 coin",
                "token": tok
              },
              "session": val
            }));
          }
        }
      }
    }
  }

  Ok(serde_json::json!({ "success": false, "hasSession": false }))
}

// ============================================================
// Tauri app entry point
// ============================================================
#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
  // Initialize license state cleanly to locked
  lic_set(false);

  // Anti-debug check at startup before UI loads
  anti_debug();

  // Activate deception matrix — 15 exotic-language fake secrets loaded into
  // memory at startup. Different every build. Confuses reverse engineers
  // who dump strings: they see Mongolian, Tibetan, Cherokee, etc.
  decoy_matrix::activate();

  #[cfg(windows)]
  {
    let _ = start_golike_bridge();

    // Kiểm tra cấu hình chuyển ổ đĩa lưu trữ (ưu tiên ổ D đến Z nếu tồn tại file .portable)
    for letter in b'D'..=b'Z' {
      let candidate = format!("{}:\\AutoLunex\\.portable", letter as char);
      if std::path::Path::new(&candidate).exists() {
        let webview_dir = format!("{}:\\AutoLunex\\webview_data", letter as char);
        #[allow(unused_unsafe)]
        unsafe {
          std::env::set_var("WEBVIEW2_USER_DATA_FOLDER", &webview_dir);
        }
        break;
      }
    }
  }

  tauri::Builder::default()
    .plugin(tauri_plugin_opener::init())
    .plugin(tauri_plugin_fs::init())
    .plugin(tauri_plugin_shell::init())
    .plugin(tauri_plugin_dialog::init())
    .plugin(tauri_plugin_clipboard_manager::init())
    // tauri_plugin_window_state removed — creates files on disk
    // tauri_plugin_log removed — creates log files on disk
    .invoke_handler(tauri::generate_handler![
      get_system_info,
      confirm_quit,
      xsmm_request,
      curl_request,
      verify_license,
      get_available_drives,
      get_current_storage_drive,
      migrate_app_to_drive,
      read_drive_data,
      open_storage_folder,
      start_app_update,
      fetch_remote_version_json,
      start_golike_bridge,
      clear_golike_session,
      extract_golike_session,
    ])
    .run(tauri::generate_context!())
    .expect("error while running tauri application");
}
